### ISSUE TITLE
Improve advance width calculation if component is flipped

### ISSUE THREAD

**Issue by yarmola** [typemytype/GlyphConstruction#21]
This is the current code to advance the width of the composite:

```
width = font[baseGlyph].width
t = Transform(*baseTransformMatrix)
width, y = t.transformPoint((width - advanceWidth, 0))
advanceWidth += width
```

It will not work very well if baseTransformMatrix is h-flipped. This implementation should be more stable:

```
t = Transform(*baseTransformMatrix)
x0, y = t.transformPoint((0, 0))
x1, y = t.transformPoint((font[baseGlyph].width, 0))
if x1 > x0:
  advanceWidth = x1
else:
  advanceWidth = x0
```

**Comment by typemytype** [comment]
could you give a glyph construction string where the output is not correct?

**Comment by colinmford** [comment]
Hey Guys,

We're having the same problem over here — @yarmola's code gives a significant improvement but it's just short of solving the problem for us.

For instance, say you would like GlyphConstruction to make a "schwa" glyph from an "e", which essentially means flipping it horizontally and vertically, and swapping the right side bearing with the left side bearing.

Attached is a UFO and a GlyphConstruction file with the situation I will describe below. For brevity sake I will list the important numbers to me in this situation — the width, rsb and lsb.

To start we have:
```
Original "e":
--------------------
width: 496
lsb: 46
rsb: 38

Expected "schwa":
--------------------
width: 496
lsb: 38
rsb: 46
``` 

Running the GlyphConstruction code below I believe should result in creating a proper schwa:
```
schwa = e @ ~origin, ~origin
```

Instead of getting a glyph with the same width as the "e", I get a glyph with these measurements:
```
Actual "schwa":
--------------------
width: 8
lsb: 46
rsb: -450
```

If I replace the existing code with @yarmola's code, I get
```
Yarmola's "schwa2":
--------------------
width: 504
lsb: 46
rsb: 46
```
Which is better, but the lsb is off.

Is there a way we can get a better flipping method so it results in the "Expected 'schwa'" above?

[Schwa GlyphConstruction Demo.zip](https://github.com/typemytype/GlyphConstruction/files/2479655/Schwa.GlyphConstruction.Demo.zip)

**Comment by typemytype** [comment]
this should be solved
thanks!

if not, please reopen
