### ISSUE TITLE
 [enhancement] lastSavedFileName vs lastBuildFileName

### ISSUE THREAD

**Issue by cjdunn** [typemytype/GlyphConstruction#45]
I noticed there's a value being stored in the lib.plist for     <key>com.typemytype.glyphBuilder.lastSavedFileName</key>

but I think it would be more helpful to save something like lastBuildFileName, since this is what actually determines the construction used. 

Just because I save a GC file with a particular UFO in the foreground doesn't mean I'm actually building that UFO with that GC file. Example: I was copy/pasting between a few GC files to keep them in sync, and seeing the file name for a different style in my git diff made me worried the accents were built incorrectly, but it was just there because I saved the GC file. Thanks for considering!

**Comment by typemytype** [comment]
this is a lib key where the file name is stored, as a glyph construction builder is a single window extension where the current font is the active one. While saving the name of the glyph construction file could be different for an other open font, so that value is used as proposed option in the save panel.

Having the latest build file as reference is dubious as the glyph construction file can change some where else.....

**Comment by cjdunn** [comment]
Ah ok, that makes sense, probably not necessary to change anything then, thanks.
